name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build, Test, and Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y capnproto libcapnp-dev libclang-dev build-essential

    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        components: clippy
        cache: true
        cache-key: queueber

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: "`map_err` is forbidden!"
      run: |
        ! git grep -E '\.map_err\(' src/**/*.rs | grep -v 'Into::'
