name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  CARGO_TERM_COLOR: always
  # TODO: for some reason it's not noticing this in .cargo/config.toml, so we have to set it here
  # rustflags = ["--cfg", "tokio_unstable"] # for tokio console
  RUSTFLAGS: --cfg tokio_unstable
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Build, Test, and Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y capnproto libcapnp-dev libclang-dev build-essential pkg-config zlib1g-dev

    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        components: clippy, rustfmt
        cache: true
        cache-key: queueber-4

    - name: Build
      run: cargo build --verbose

    - name: Run tests (verbose, no capture)
      run: cargo test --verbose -- --nocapture

    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: "`map_err` is forbidden!"
      run: |
        ! git grep -E '\.map_err\(' src/**/*.rs | grep -v 'Into::'
